name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Analyze warp_user
      working-directory: ./warp_user
      run: |
        flutter pub get
        flutter analyze

    - name: Test warp_user
      working-directory: ./warp_user
      run: flutter test

    - name: Build warp_user APK
      working-directory: ./warp_user
      run: flutter build apk --debug

    - name: Analyze warp_driver
      working-directory: ./warp_driver
      run: |
        flutter pub get
        flutter analyze

    - name: Test warp_driver
      working-directory: ./warp_driver
      run: flutter test

    - name: Build warp_driver APK
      working-directory: ./warp_driver
      run: flutter build apk --debug
